protected/controllers/CartController.php
<?php

class CartController extends WebController
{
	
	
	
	private function taxesForProvinceCountryValue($province, $country, $value){
		
		// Calculate taxes
		
		if ($country === "CA"){
			// Calculate taxes
			
			if ($province === "AB"){
				return $value * 0.05;
			} else if  ($province === "BC"){
				return $value * 0.05;
			}  else if  ($province === "MB"){
				return $value * 0.05;
			} else if  ($province === "NB"){
				return $value * 0.13;
			} else if  ($province === "NS"){
				return $value * 0.15;
			} else if  ($province === "ON"){
				return $value * 0.13;
			} else if  ($province === "PE"){
				return $value * 0.14;
			} else if  ($province === "QC"){
				return $value * 0.1498;
			} else if  ($province === "SK"){
				return $value * 0.05;
			} else if  ($province === "NT"){
				return $value * 0.05;
			} else if  ($province === "NU"){
				return $value * 0.05;
			} else if  ($province === "YT"){
				return $value * 0.05;
			} else {
				return $value * 0.1498;
			}
			
		} else {
			return 0.0;
		}
		
	}
	
	
	private function subtotalForCart($cart){
		
		$dataProvider=new CActiveDataProvider('OrderHasProduct', array(
		    'criteria'=>array(
		        'condition'=>'order_id=' . $cart->id,
		        'with'=>array('product'),
		    ),
		    'pagination'=>false
		));
		
		// Produce the subtotal
		$total_value = 0.0;
		$total_item_qty = 0;
		foreach ($dataProvider->getData() as $relationship){
			$total_value += $relationship->quantity * $relationship->price_paid;
			$total_item_qty += $relationship->quantity;
		}
		
		return $total_value;
		
	}
	
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'postOnly + redeem, add, remove, update, estimate, prepare, order, addmultiple',
			'ajaxOnly + add, remove, update, estimate, prepare, order, addmultiple, overview, details, redeem, chargePaypal',
		);
	}
	
	
	public function actionRedeem(){
		
		$cart = $this->getCart();
		
		$promocode = strtoupper(Yii::app()->request->getPost("coupon", null));
		
		if (!$promocode || $promocode === ""){
			throw new CHttpException(400,'The request is invalid.');
		}
		
		$coupon_array = array();
		if ($promocode === "FALL14"){
			
			Yii::app()->session['applicable_rebate'] = 0.15;
			Yii::app()->session['promocode'] = "FALL14";
			
			// Apply the coupon to items already in the cart
			$itemsInCart = OrderHasProduct::model()->findAll("order_id=:order_id", array(":order_id"=>$cart->id));
			
			foreach ($itemsInCart as $relationship){
					$relationship->price_paid = $relationship->product->getCurrentPrice();
					$relationship->save();
			}
			
			// Build a json array that could be used by our 
			
			$coupon_array["valid"] = true;
			$coupon_array["code"] = Yii::app()->session['promocode'];
			$coupon_array["expired"] = false;
			$coupon_array["type"] = "percent";
			$coupon_array["details"] = array("rebate"=>Yii::app()->session['applicable_rebate']*100);
		} else {
			$coupon_array["valid"] = false;
		}
		
		$this->renderJSON($coupon_array);
		
		
	}
	
	
	public function actionPrepare(){
		
		$country = Yii::app()->request->getPost("country", null);
		$province = Yii::app()->request->getPost("province", null);
		$postcode = Yii::app()->request->getPost("postalcode", null);
		$shipping_type = Yii::app()->request->getPost("shipping_type", null);
		
		$shipping_estimated_value = Yii::app()->request->getPost("shipping_estimated_value", null);
		
		if ($country === null || $shipping_type === null || $shipping_estimated_value === null){
			throw new CHttpException(400,'The request is invalid.');
		}
		
		$cart = $this->getCart();
		
		if ($cart->orderDetails){
			$details = new OrderDetails;
			$details->order_id = $cart->id;
			$details->save();
		} else {
			// We need to create an order details object
			$details = $cart->orderDetails;
		}
		
		
		
		$details->subtotal = $this->totalItemCount($cart);
		$details->taxes = $this->taxesForProvinceCountryValue($province, $country, $details->subtotal);
		$details->shipping = $shipping_estimated_value;
		$details->shipping_type = $shipping_type;
		$details->save();
		
		
	}
	
	public function actionCheckout()
	{
		$this->can_prompt_for_password_set = false;
		$country = Yii::app()->request->getPost("country", null);
		$province = Yii::app()->request->getPost("province", null);
		$postcode = Yii::app()->request->getPost("postalcode", null);
		$shipment = Yii::app()->request->getPost("shipment", null);
		
		// Set the shipment in the session
		Yii::app()->session['shipment_method'] = $shipment;
		
		$cart = $this->getCart();
		
		if (!$cart || Yii::app()->user->isGuest){
			$this->redirect("/panier.html");
		}
		
		
		
		$this->render('checkout', array('subtotal'=>$this->subtotalForCart($cart), 'country'=>$country, "province"=>$province, "postcode"=>$postcode, 'shipment'=>$shipment, 'subtotal'=>$this->subtotalForCart($cart)));
		
	}
	
	
	public function actionGetPaypalToken(){
		
		
		$country = Yii::app()->request->getPost("country", null);
		$province = Yii::app()->request->getPost("province", null);
		$postcode = Yii::app()->request->getPost("postalcode", null);
		$shipment = Yii::app()->request->getPost("shipment", null);
		
		
		// Temporary promocode stuff
		/*
		$promocode = strtoupper(Yii::app()->request->getPost("promocode", null));
		if ($promocode === "FALL14"){
			Yii::app()->session['applicable_rebate'] = 0.15;
		}
		// Temporary promocode stuff
		*/
		
		if (!$country || !$postcode || !$shipment){
			throw new CHttpException(400,'Invalid request: missing parameters.');
		}
		
		// Set the shipment in the session
		Yii::app()->session['shipment_method'] = $shipment;
		
		$cart = $this->getCart();
		
		
		// Save every detail for the order total price and taxes based on the provided shipping address
		$itemsInCart=new CActiveDataProvider('OrderHasProduct', array(
		    'criteria'=>array(
		        'condition'=>'order_id=' . $cart->id,
		        'with'=>array('product'),
		    ),
		    'pagination'=>false
		));
		
		$total_weight = 0.0;
		$total_value = 0.0;
		$total_item_qty = 0;
		foreach ($itemsInCart->getData() as $relationship){
			
			/*
			if ($promocode){
				$relationship->price_paid = $relationship->product->getCurrentPrice();
				$relationship->save();
			}*/
			
			$total_weight += $relationship->quantity * $relationship->product->weight;
			$total_value += $relationship->quantity * $relationship->price_paid;
			$total_item_qty += $relationship->quantity;
		}
		
		// Build the json request data we'll send to our server
		$weight = $total_weight;
		$handling = 0;
		$postal_code = $postcode;
		$country_code = $country;
		$value = $total_value;
		$qty = $total_item_qty;
		
		$orderData = array("weight"=>$weight, "handling"=>$handling, "postal_code"=>$postal_code, "country_code"=>$country_code, "value"=>$value, "qty"=>$qty);
		
		
		$jsonpayload = json_encode($orderData);
		
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL,            "https://kle-en-main.com/CloudServices/index.php/BoukemAPI/canadaPostEstimate/listServices?storeid=" . Yii::app()->params['outbound_api_user'] . "&storekey=" . Yii::app()->params['outbound_api_secret'] );
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1 );
		curl_setopt($ch, CURLOPT_POST,           1 );
		curl_setopt($ch, CURLOPT_POSTFIELDS,     $jsonpayload ); 
		curl_setopt($ch, CURLOPT_HTTPHEADER,     array('Content-Type: application/json')); 
		$result=curl_exec ($ch);
		
		curl_close($ch);
		
		$arr = json_decode($result);
		
		if (!isset($arr->services)){
			throw new CHttpException(400,Yii::t("app", "Postes Canada ne peut fournir d'estimé en ce moment."));
		}
		$rates = $arr->services;
		
		if ($rates === null){
			throw new CHttpException(400,Yii::t("app",'Une erreur est survenue.'));
		}
		
		$preferred_method = Yii::app()->session['shipment_method'];
		$shiprate = null;
		foreach ($rates as $rate) {
			
			if ($rate->service_code === $preferred_method){
				$shiprate = $rate->price_due;
				break;
			}
			
		}
		
		
		if ($shiprate === null){
			throw new CHttpException(400,'The delivery method specified in the cart is not available.');
		}
		
		
		
		// TAXES
		
		$order_details = $cart->orderDetails;
		if ($order_details === null){
			$order_details = new OrderDetails;
			$order_details->order_id = $cart->id;
		}
		
		$order_details->shipping = $shiprate;
		$order_details->shipping_type = $preferred_method;
		
		$order_details->taxes = round($this->taxesForProvinceCountryValue($province, $country, $total_value), 2);
		$order_details->subtotal = round($total_value, 2);
		$order_details->total = round(floatval($order_details->subtotal) + floatval($order_details->taxes) + floatval($order_details->shipping), 2);
		$order_details->balance = $order_details->total;
		
		$order_details->save();
		
		
		// Transform the cart in order to avoid deleting it.
		$cart->status = "pending";
		$cart->save();
		
		
		$order = $cart;
		$order->orderDetails = $order_details;
		
		$paypal_link = $order->getPaypalPaymentLink();
		$this->renderJSON(array("paypal_url"=>$paypal_link));
		
	}

	public function actionIndex()
	{
		
		$this->can_prompt_for_password_set = false;
		$this->breadcrumbs=array(
			Yii::t("app", 'Panier'),
		);
		
		$cart = $this->getCart();
		
		$dataProvider=new CActiveDataProvider('OrderHasProduct', array(
		    'criteria'=>array(
		        'condition'=>'order_id=' . $cart->id,
		        'with'=>array('product'),
		    ),
		    'pagination'=>false
		));
		
		
		$this->render('index', array("dataProvider"=>$dataProvider, 'subtotal'=>$this->subtotalForCart($cart), 'quantity'=>$dataProvider->totalItemCount));
	}
	
	/*
	 * Cart operations
	 */
	
	public function actionAdd()
	{
		$product = Product::model()->findByPk(Yii::app()->request->getPost('product'));
		$quantity = Yii::app()->request->getPost('quantity', "1");
		
		if ($product === null){
			throw new CHttpException(404,'Invalid product.');
		}
		
		$cart = $this->getCart();
		
		

protected/controllers/CssController.php
<?php

class CssController extends WebController
{
	
	protected function adjustBrightness($hex, $steps) {
	    // Steps should be between -255 and 255. Negative = darker, positive = lighter
	    $steps = max(-255, min(255, $steps));

	    // Normalize into a six character long hex string
	    $hex = str_replace('#', '', $hex);
	    if (strlen($hex) == 3) {
	        $hex = str_repeat(substr($hex,0,1), 2).str_repeat(substr($hex,1,1), 2).str_repeat(substr($hex,2,1), 2);
	    }

	    // Split into three parts: R, G and B
	    $color_parts = str_split($hex, 2);
	    $return = '#';

	    foreach ($color_parts as $color) {
	        $color   = hexdec($color); // Convert to decimal
	        $color   = max(0,min(255,$color + $steps)); // Adjust color
	        $return .= str_pad(dechex($color), 2, '0', STR_PAD_LEFT); // Make two char hex code
	    }

	    return $return;
	}
	
	protected function getCssFilesList(){
		
		$themePath = Yii::app()->theme->baseUrl;
		$main_style_sheet = '/css/global-style.css';
		if (file_exists(Yii::app()->basePath . "/.." . $themePath . $main_style_sheet)){
			$main_style_sheet = $themePath . $main_style_sheet;
		}

		$secondary_style_sheet = '/css/skin-four.css';
		if (file_exists(Yii::app()->basePath . "/.." . $themePath . $secondary_style_sheet)){
			$secondary_style_sheet = $themePath . $secondary_style_sheet;
		}
		
		
		$cssFiles = array(
		Yii::app()->basePath . "/../" . $main_style_sheet,
		Yii::app()->basePath . "/../" . $secondary_style_sheet,
		Yii::app()->basePath . "/../css/cart-drawer.css",
		);
		return $cssFiles;
	}

	/**
	 * Mash up our css and replace some values when custom values are available on KEM Console.
	 */
	public function actionCustom()
	{
		
		$cache_id = "CustomBoukemCss";
		$cache_duration = 3600;
		
		$customCss = Yii::app()->cache->get($cache_id);
		
		if (!$customCss){
			
			$request_parameters = array('storeid'=>Yii::app()->params['outbound_api_user'], 'storekey'=>Yii::app()->params['outbound_api_secret']);
			$output = Yii::app()->curl->get("https://kle-en-main.com/CloudServices/index.php/BoukemAPI/colors/index", $request_parameters);
			
			$base_dict = json_decode($output);
			
			// Concatenate all customizable css files
			$buffer = "";
			foreach ($this->getCssFilesList() as $cssFile) {
			  $buffer .= file_get_contents($cssFile);
			}

			// Remove comments
			$buffer = preg_replace('!/\*[^*]*\*+([^/][^*]*\*+)*/!', '', $buffer);

			// Remove space after colons
			$buffer = str_replace(': ', ':', $buffer);
			
			if (isset($base_dict->color_one)){
				$buffer = str_replace('#f0523f', '#' . $base_dict->color_one, $buffer);
				$buffer = str_replace('#e06d58', $this->adjustBrightness($base_dict->color_one, -45), $buffer);
				$buffer = str_replace('#dc402e', $this->adjustBrightness($base_dict->color_one, -75), $buffer);
			}
			
			if (isset($base_dict->color_two)){
				$buffer = str_replace('#2d93ff', '#' . $base_dict->color_two, $buffer);
				$buffer = str_replace('#7a92ac', $this->adjustBrightness($base_dict->color_two, -75), $buffer);
				
			}
			
			if (isset($base_dict->color_three)){
				$buffer = str_replace('#ecebec', '#' . $base_dict->color_three, $buffer);
				$buffer = str_replace('#f2f2f2', $this->adjustBrightness($base_dict->color_three, +25), $buffer);
				
			}
			
			if (isset($base_dict->color_four)){
				$buffer = str_replace('#2d2d2d', '#' . $base_dict->color_four, $buffer);
			}
			
			if (isset($base_dict->color_five)){
				$buffer = str_replace('#4c4c4c', '#' . $base_dict->color_five, $buffer);
				$buffer = str_replace('#777', $this->adjustBrightness($base_dict->color_five, -75), $buffer);
				$buffer = str_replace('#999', $this->adjustBrightness($base_dict->color_five, +95), $buffer);
				$buffer = str_replace('#ccc', $this->adjustBrightness($base_dict->color_five, 75), $buffer);
				$buffer = str_replace('#31363a', $this->adjustBrightness($base_dict->color_five, -150), $buffer);
			}
			
			if (isset($base_dict->injected)){
				$buffer .= $base_dict->injected;
			}
			
			$buffer = str_replace(array("\r\n", "\r", "\n", "\t", '  ', '    ', '    '), '', $buffer);
			
			Yii::app()->cache->set($cache_id, $customCss, $cache_duration);
		}
		
		
		ob_start("ob_gzhandler");

		// Enable caching
		header('Cache-Control: public');

		// Expire in one day
		header('Expires: ' . gmdate('D, d M Y H:i:s', time() + $cache_duration) . ' GMT');

		// Set the correct MIME type, because Apache won't set it for us
		header("Content-type: text/css");

		// Write everything out
		echo($buffer);
		
	    foreach (Yii::app()->log->routes as $route) {
	        if($route instanceof CWebLogRoute) {
	            $route->enabled = false; // disable any weblogroutes
	        }
	    }
	    Yii::app()->end();
	}

	
}

protected/views/layouts/_footer.php
<footer>
    <div class="container">
		
		<div class="row">
			<?php if (!$this->isB2b()): ?>
            <div class="col-md-4">
            	<div class="col">
                   <h4><?php echo Yii::t('app', 'Information'); ?></h4>
      			<ul>
      				<li><a href="<?php echo $this->createUrl('site/page', array('view'=>'about')); ?>"><?php echo Yii::t('app', 'À propos de la boutique'); ?></a></li>
      				<li><a href="<?php echo $this->createUrl('site/page', array('view'=>'privacy')); ?>"><?php echo Yii::t('app', 'Politique de confidentialité'); ?></a></li>
      				<li><a href="<?php echo $this->createUrl('site/page', array('view'=>'terms')); ?>"><?php echo Yii::t('app', "Conditions d'utilisation"); ?></a></li>
      				<li><a href="<?php echo $this->createUrl('site/page', array('view'=>'shipping')); ?>"><?php echo Yii::t('app', "Méthodes d'expédition"); ?></a></li>
      			</ul>
                 </div>
            </div>
            
            <div class="col-md-4">
            	<div class="col">
                    <h4><?php echo Yii::t('app', 'Accès rapide'); ?></h4>
        			<ul>
        				<li><a href="catalogue.html"><?php echo Yii::t('app', 'Accueil'); ?></a></li>
						<?php
						echo $category_links_html;
						?>
        			</ul>
                </div>
            </div>
            <?php endif; ?>
            
             <div class="col-md-4">
             	<div class="col">
                    <h4><?php echo Yii::t('app', 'Service à la clientèle'); ?></h4>
        			<ul>
        				<li><a href="<?php echo $this->createUrl('site/page', array('view'=>'contact')); ?>"><?php echo Yii::t('app', 'Nous contacter'); ?></a></li>
        				<li><a href="<?php echo $this->createUrl('site/page', array('view'=>'returns')); ?>"><?php echo Yii::t('app', 'Retours et échanges'); ?></a></li>
        				<li><a href="<?php echo $this->createUrl('account/index'); ?>"><?php echo Yii::t('app', 'Compte'); ?></a></li>
				  		  <?php if (Yii::app()->user->isGuest):?>
		  
				  		  <li><a href=""><?php echo CHtml::link(Yii::t('app', 'Devenir membre ou se connecter'), array('site/register')); ?></a></li>
		  
				  	  <?php else: ?>
		  
				  		  <li><?php echo CHtml::link(Yii::t('app', 'Se déconnecter'), array('site/logout')); ?></li>
		  
				  		  <?php endif;?>
        			</ul>
                </div>
            </div>
			
        </div>
		
	
	  <hr />
        <div class="row">
        	<div class="col-lg-9 copyright">
            	&copy; <?php echo date("Y"); ?>, <?php echo Yii::t('app', 'tous droits réservés'); ?>.
            </div>
            <div class="col-lg-3 footer-logo text-right">
            	<img src="/images/kem_signature.png" alt="Powered by KEM">
            </div>
        </div>
    </div>
</footer><!-- JavaScript -->

protected/views/layouts/_footer_invisibles.php
<div id="modal_cart"></div>
<div id="cart-container">
	<div class="proceed btn-group btn-group-justified">
		<a class="btn btn-two btn-lg" id="back"><?php echo Yii::t("app", "Continuer le magasinage"); ?></a>
		<?php echo CHtml::link(Yii::t("app", "Passer à la caisse"), "/cart/index", array('class'=>'btn btn-three btn-lg', 'id'=>'checkout')); ?>
	</div>
	<div id="cart-items">
		<ul class="cart-items-list">            
		</ul>
	</div>
</div>

<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://analytics.kem.guru/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', <?php echo Yii::app()->params['kem_analytics_id']; ?>]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript';
    g.defer=true; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//analytics.kem.guru/piwik.php?idsite=<?php echo Yii::app()->params['__KEM_ANALYTICS_ID__']; ?>" style="border:0;" alt="" /></p></noscript>
<?php
if (isset(Yii::app()->params["google_analytics_tracking_id"]) && Yii::app()->params["google_analytics_tracking_id"] !== null): 
?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?php echo Yii::app()->params["google_analytics_tracking_id"]; ?>', 'auto');
  ga('send', 'pageview');
  <?php if (!Yii::app()->user->isGuest): ?>ga('set', '&uid', "<?php echo Yii::app()->user->user->id; ?>");<?php endif; ?>
</script>
<?php endif; ?>

protected/views/layouts/_head.php
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="icon" href="/favicon.png" />
	<?php if ($this->pageDescription): ?>
		<meta name="description" content="<?php echo CHtml::encode($this->pageDescription); ?>">
	<?php endif; ?>
    
    <title><?php if ($this->isHomePage){
    	echo Yii::app()->name;
    } else {
    	echo CHtml::encode($this->pageTitle) . " - " . Yii::app()->name;
    }; ?></title>

<?php foreach ($this->alternatives as $key => $value) {
	echo '<link rel="alternate" hreflang="' . $key . '" href="' . $value . '" />';
}?>

<?php
$cs = Yii::app()->clientScript;

/**
 * StyleSHeets
 */
$cs
	->registerCssFile('https://cdn.kem.guru/boukem/spirit/css/outdatedbrowser.min.css')
    ->registerCssFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css')
	->registerCssFile('https://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
	//->registerCssFile('/js_assets/fancybox/jquery.fancybox.css?v=2.1.5')
	//->registerCssFile('/js_assets/fraction/fractionslider.css')
	
	->registerCssFile('https://cdn.kem.guru/boukem/spirit/css/fancybox-fraction-concat.css')
	->registerCssFile($this->createUrl("css/custom"));


/**
 * JavaScripts
 */
$cs
	->registerScriptFile('https://cdn.kem.guru/boukem/spirit/js/outdatedbrowser.min.js',CClientScript::POS_HEAD)
    ->registerCoreScript('jquery',CClientScript::POS_END)
    //->registerCoreScript('jquery.ui',CClientScript::POS_END)
    ->registerScriptFile('https://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js',CClientScript::POS_END)
	->registerScriptFile('https://cdn.kem.guru/boukem/spirit/js/gcc_ressources.js.gz',CClientScript::POS_END)
	//->registerScriptFile('https://cdn.kem.guru/boukem/spirit/js/bootstrap.touchspin.js',CClientScript::POS_END)
	//->registerScriptFile('https://cdn.kem.guru/boukem/spirit/js/modernizr.custom.js',CClientScript::POS_END)
	//->registerScriptFile('https://cdn.kem.guru/boukem/spirit/js/jquery.mousewheel-3.0.6.pack.js',CClientScript::POS_END)
	//->registerScriptFile('https://cdn.kem.guru/boukem/spirit/js/jquery.cookie.js',CClientScript::POS_END)
	//->registerScriptFile('https://cdn.kem.guru/boukem/spirit/js/jquery.easing.js',CClientScript::POS_END)
	//->registerScriptFile('/js_assets/masonry/masonry.js',CClientScript::POS_END)
	//->registerScriptFile('/js_assets/page-scroller/jquery.ui.totop.min.js',CClientScript::POS_END)
	//->registerScriptFile('/js_assets/mixitup/jquery.mixitup.js',CClientScript::POS_END)
	->registerScriptFile('/js_assets/mixitup/jquery.mixitup.init.js',CClientScript::POS_END)
	->registerScriptFile('/js_assets/fancybox/jquery.fancybox.pack.js?v=2.1.5',CClientScript::POS_END)
	//->registerScriptFile('/js_assets/fraction/jquery.fractionslider.min.js',CClientScript::POS_END)
	->registerScriptFile('/js_assets/fraction/jquery.fractionslider.init.js',CClientScript::POS_END)
	//->registerScriptFile('https://cdn.kem.guru/boukem/spirit/js/imagesloaded.pkgd.min.js',CClientScript::POS_END)
	->registerScriptFile('https://cdn.kem.guru/boukem/spirit/js/jquery.ebright.custom.js.gz',CClientScript::POS_END)
	->registerScriptFile('/js/boukem.js',CClientScript::POS_END)
	
		
    ->registerScript('tooltip',
        "outdatedBrowser({bgColor: '#f25648',color: '#ffffff',lowerThan: 'borderImage',languagePath: ''});
$('[data-toggle=\"tooltip\"]').tooltip();
$('[data-toggle=\"popover\"]').tooltip();
",CClientScript::POS_READY);
		
		
	
		if ($this->isB2b()){
			$cs->registerScriptFile('/js/boukemb2b.js',CClientScript::POS_END);
			$redirect_domain = Yii::app()->language === "fr" ? "https://kle-en-main.com" : "https://kemsolutions.com";
		}

?>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
    <script src="//cdn.kem.guru/boukem/spirit/js/html5shiv.js"></script>
    <script src="//cdn.kem.guru/boukem/spirit/js/respond.min.js"></script>
<![endif]-->

protected/views/layouts/_search.php
<!-- SEARCH -->
<div class="search-wr" id="divSearch">
	<span class="close" id="cmdCloseSearch" title="Fermez la recherche en cliquant sur ce bouton ou en appuyant sur la touche ESC"><i class="fa fa-times-circle"></i></span>
	<div class="container">
    	<div class="row">
        	<div class="col-md-1 col-xs-2 search-sign">
            	<i class="fa fa-search"></i>
            </div>
            <div class="col-md-11 col-xs-10">
				<form  method="get" action="<?php echo $this->createUrl('product/search'); ?>">
            	<input type="text" name="q" autofocus class="global-search-input" placeholder="<?php echo Yii::t("app", "Rechercher"); ?>" value="" autocomplete="off" spellcheck="false" dir="ltr">
			</form>
			</div>
            </div>
        </div>
    </div>
</div>

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>

<!-- PAGE INFO -->
<div class="pg-opt pin">
	<div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2><?php echo $this->pageTitle; ?></h2>
            </div>
	            <?php 
				if ($this->breadcrumbs):
				?>
				<div class="col-md-6">
                
						<?php $this->widget('zii.widgets.CBreadcrumbs', array(
						    'links'=>$this->breadcrumbs,
							'separator'=>"",
							'tagName'=>'ol',
							'homeLink'=>false,
							'htmlOptions'=>array('class'=>"breadcrumb"),
							'activeLinkTemplate'=>'<li><a href="{url}">{label}</a></li>',
							'inactiveLinkTemplate'=>'<li class="active">{label}</li>',
						));
						?>
                    
	            </div>
			<?php 
			endif;
	             ?>
        </div>
    </div>
</div>


<section class="slice color-three column1_main_slice">
	<div class="w-section inverse">
    	<div class="container">
			<div class="row">
			<div class="col-xs-12">
			<?php echo $content; ?>
		</div>
	</div>
</div><!-- content -->
</div>
</section>
<?php $this->endContent(); ?>